### ISSUE TITLE
Don't support for the FreeBSD 11...

### ISSUE THREAD

**Issue by mrwert** [janvidar/quickdc#1]
:(

**Comment by janvidar** [comment]
I don't think it ever will. I stopped working on this actively more than a decade ago, and this was using Qt3 and equivalent KDE libraries  at the time.

**Comment by mrwert** [comment]
Sorry, tell me please how i can to fix this warning "NET: xxx.xxx.xxx.xxx requested active connection [xxx.xxx.xxx.xxx:xxx]"?
